package relojanalogico1;

import java.awt.Color;
import java.awt.Graphics;

public class PixelArt {
    private String kirby[][] = {
 {"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "e0e0e0", "dededc", "dddddd", "dddddd", "dddddd", "d8d2d2", "14171c", "242128", "212025", "0e1213", "dfdfdd", "959597", "dcdcdc", "e2e2e2", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dcdcda", "161a1d", "50492c", "241e00", "1a1511", "dddddb", "16171c", "1b2024", "f6a2c4", "f9a3c8", "f49ec1", "fca6c9", "222126", "bf2b29", "ab3237", "8b2c32", "d6d5da", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddf", "23262d", "78d115", "edd729", "f7e52d", "323000", "6f4c64", "1c0f19", "ffaccf", "fba5c8", "f29bbe", "fda5cb", "eea1c1", "af3534", "b72c29", "ba312b", "b32c29", "1e1d23", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "14141c", "7bd418", "fdea36", "fbe72e", "ffee36", "18171d", "fdb0d0", "feadce", "feadce", "f39fc1", "f2a0c4", "ffacce", "ffabd0", "b32f2b", "b82f27", "bf342f", "b7332f", "1a191f", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "151316", "7cd521", "7ada1e", "f5e32b", "feeb2f", "10131c", "ffa9cf", "ffb1d4", "ffb2d3", "ffb6d4", "dd5cd2", "f7a8c8", "ffaacd", "f7a1c4", "1f1820", "bd2c27", "b62f29", "bb3431", "1d1c22", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "2d2e33", "82d02e", "7fd41e", "f9e72d", "feea33", "f9e429", "1d161e", "f39bc1", "ea96b8", "f59fc4", "f59cbc", "db52d6", "ffb7d7", "ffafd0", "f09fc0", "ffb6d5", "1e1510", "b72e28", "bc3230", "1f1e24", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "ededef", "1b2713", "82d128", "78ce15", "fdeb33", "feea33", "887e29", "ffabcf", "fafeff", "f7ffff", "1498ad", "192426", "fda3c9", "f29bbe", "fda5cb", "f8a4c6", "ffabce", "faa3c6", "3b0b09", "b8312e", "212026", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "333436", "0e1d0a", "8de22c", "7ad317", "fcea32", "f9e931", "89852e", "fda3c7", "1f111e", "261f26", "1c101c", "212429", "fea7ca", "b75d69", "ffacd1", "fba5c8", "ffa9cd", "f99bc0", "f3b8d4", "1e1c27", "111217", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "323337", "12210c", "8ce52b", "80d61d", "fbe931", "f1e129", "83812a", "ee9ec1", "faa9ca", "f9a8c9", "ffaecf", "feadce", "faa6c8", "af5561", "ffadd1", "fdaccd", "ffaacf", "fca6c9", "fda1c6", "1a1b20", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "303133", "182313", "83dd25", "80d51f", "fff23a", "fdeb31", "827e27", "ffacd2", "f9fffd", "f3feff", "27a6b7", "261f27", "f2a0c6", "eb96ab", "fcaccf", "f3a2c3", "ffafd2", "fca8ca", "f8a4c8", "1a1b20", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "28292d", "1c2918", "7dd61a", "77cd14", "f8e42b", "f5e62b", "8a892f", "ef91b6", "1b161d", "18171c", "191d1e", "111217", "fba9cf", "fdadd0", "faa6c8", "fdaccd", "ffb1d4", "faa4c7", "faa6ca", "1a1b20", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "2d2e32", "0e1a0c", "7bd31c", "76cb16", "f6e229", "fbe72e", "86822b", "f79dc1", "f89cc1", "faa0c4", "f99ac2", "ffa3d0", "d445d2", "f69fc2", "fda3c7", "f59ec1", "fea4c8", "f49ec1", "e2aac3", "1e1e26", "12121c", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "25262a", "162312", "7ad319", "7ed31d", "fae62f", "f6e229", "877b25", "ffa9ce", "f4a2c6", "ffadd2", "ee9dbe", "ffaccf", "da4ed3", "f29cbf", "fda7ca", "ffacce", "ffabce", "fda7ca", "441a1b", "b02c28", "1e1d23", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddf", "dadada", "161618", "152219", "90d143", "77cb13", "e0d545", "36192f", "8f536d", "fda9cb", "faa8cc", "ffb0d1", "f7aaca", "faa8ce", "d55dbf", "f2a1c2", "ffaecf", "fdabcf", "ffadd2", "e4acc5", "691312", "b82e2c", "1c1b21", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dbdcd7", "191c21", "27888e", "40a7ac", "3e4da0", "082209", "e8a3c2", "f6a2c4", "f2a1c2", "f3a2c3", "f9a8c9", "fbaacb", "fcaccf", "ffb1d5", "f1a0c1", "fdabcf", "ffb0d1", "f2a3c3", "3a1f2e", "bb2b2a", "bc332b", "ba3330", "201f25", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dedcdd", "0d1719", "3b44b9", "3641b7", "2ea4c0", "454ac0", "161c1c", "f4a7c9", "f5a3c7", "ffacd0", "ffb4d4", "ffb3d3", "ffb7d8", "feaacc", "fdaccd", "ffaed2", "f39fc0", "f4a2c6", "211e25", "c1302b", "bf342f", "b52e2b", "131217", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dcdcdc", "1c1920", "3f49c2", "434fc5", "179cab", "0f171a", "f4a7c9", "fda9cb", "faa3c6", "f69fc2", "ea99ba", "f19abd", "ffa8cb", "f29ec0", "f59fc2", "fda3c7", "fca8ca", "b6312c", "ba332d", "b62f29", "b32c29", "212025", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "1c1f28", "15151d", "15151d", "101116", "12151c", "ab6c49", "4444a6", "3e41b4", "12a0ac", "13181c", "ffa7cd", "f59ec1", "fba4c7", "ffadd0", "f29ec0", "ffaacd", "ffa8cb", "f69fc2", "ffafd2", "f7b2cf", "af4245", "b9322c", "be352f", "bb312f", "1c1b21", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "1c1d22", "1c1d21", "1e1f23", "25262a", "202328", "1a1d22", "191c21", "202328", "191c21", "1a1b20", "4245b0", "1a9ea3", "52d9ff", "35c0e7", "f4e729", "d49432", "b6724d", "3940b4", "13a0aa", "14191d", "f9a2c5", "ffa9cc", "eda2c1", "ffafd1", "ec9bbc", "fcb5d3", "ecb4cd", "ae7890", "909090", "e0e0e2", "d1d1d3", "1c0e0b", "bd322d", "ba3330", "1f1e23", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "141519", "22aebb", "45cff6", "43d6f8", "55e8ff", "46cffb", "36c5f1", "4fd6ff", "34c0e4", "4cd3ff", "45d4ff", "40ceff", "51d8ff", "49d3ff", "4ad3fd", "d69a2c", "c3d1ba", "b37550", "3c46b9", "1da7b4", "1b1e23", "eaa3c1", "e0a4c0", "323c24", "181816", "f3ea5d", "fbee50", "141519", "dddce1", "dddddd", "dddddd", "dcdcda", "0f1014", "1e1822", "0f1620", "dbdbdd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "181820", "27a5b4", "3ac4f2", "fcfefd", "feffff", "50d5ff", "35c0eb", "4dd8ff", "47d2f9", "42cdf4", "49d7ff", "3cc5f1", "49d2ff", "42cbf7", "1aa5ac", "19a3ad", "ad7053", "ab6130", "403fa7", "3643b3", "13a3ab", "130c14", "73804a", "798749", "74893e", "fff332", "ffef37", "fdea34", "fff23e", "d1d1d3", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "1c2023", "18a4b1", "3cc9f6", "fafcfb", "fbfdfc", "feffff", "fefefe", "3ec7f3", "45d0fb", "3ec9f4", "48d2ff", "45d2ff", "32b9d6", "1a9cac", "199faa", "4a51c5", "1d1e22", "333438", "17181d", "4148b2", "2491b8", "3b49b4", "121816", "434e23", "74893e", "778b43", "fcee35", "ffeb30", "ffec2e", "f7e32c", "d4d4d6", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "171b1e", "1ba5b2", "4cd5ff", "f7fff4", "fcfdff", "fdfffe", "fcfefd", "fdfffe", "f9ffff", "4ed9ff", "189eaa", "1ea4b0", "18a5ae", "129fa6", "354bae", "23212e", "474749", "dddddd", "dddddd", "2f3035", "3ca5b8", "4244bd", "24212a", "dcdedd", "27262c", "151419", "16171c", "f7e72f", "f6e22b", "ffee37", "ffea3c", "e7e7e5", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "1d1b26", "17a7af", "4ed7ff", "fcfffd", "fdfdfd", "fcfefd", "fdfffe", "fdfffe", "fdfffe", "fcffff", "28aeba", "1aa2ae", "28acbb", "2d9ab7", "1d2458", "57565b", "e0e0e0", "dddddd", "dddddd", "dddddd", "2d2e32", "232323", "181a19", "dedde2", "dddddd", "dddddd", "dedcdf", "d4d4d4", "231f20", "f8e531", "fff04a", "232522", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "1a1b20", "24a2b1", "45cffd", "fbfdfc", "fafcf9", "fbfdfc", "fdfffe", "fcfefd", "feffff", "feffff", "159fa9", "1ca6b3", "1ea9ac", "4a52b5", "262729", "c6c6c8", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "7c7b80", "59595b", "e7e7e9", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "212227", "1b1b1b", "1a2224", "3941ae", "fbfcfe", "fbfdfc", "fcfdff", "fdfef9", "fefefc", "fdfffa", "13a5a5", "20a1a7", "1c1d21", "5c5d61", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "e0e0e0", "dddddd", "dddddd", "0e1118", "090913", "14151a", "17161c", "3940b5", "1ba1aa", "48d4f5", "343aaa", "26252a", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dedcdf", "deddd9", "1f1e24", "312f32", "1c1b21", "29282e", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},
{"dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd", "dddddd"},

};
    
    public void pintarKirby(Graphics gFondo, int x, int y, int tamano){
        for (int i = 0; i < kirby.length; i++) {
                for (int j = 0; j < kirby[i].length; j++) {
                    gFondo.setColor(new Color(Integer.parseInt(kirby[i][j], 16)));
                    gFondo.fillRect(i*tamano+x, j*tamano+y, tamano, tamano);
                }
            }
    }
    
}
