package herramientas;

public class PoolFrases {

    public static String[] frases
            = {
                "No me alcanza ni para el Oxxo",
                "Ya ni la muelas",
                "Todo bien, pero nada esta bien",
                "Andamos al 100",
                "Estoy bien, pero bien cansado",
                "Con toda la facha",
                "No estoy triste, solo traigo sueno",
                "Modo diablo activado",
                "Hoy no ando para nadie",
                "F por mi",
                "Épico",
                "XD",
                "Alta facha",
                "Nivel Dios",
                "Que bendicion",
                "Ya valio",
                "Soy yo, el problema soy yo",
                "Tranqui, fiera",
                "Se tenia que decir y se dijo",
                "Chale",
                "No se dice wow, se dice 'ahuevo'",
                "Te mando un sticker mejor",
                "Estoy bien broke",
                "Sin miedo al exito",
                "Ni modo, cotorreo sano",
                "Callese senora",
                "Ahi nos vidrios",
                "Y si si, ¿que?",
                "No era penal",
                "La neta, si jalo",
                "Se tenia que rifar y se rifo",
                "Ando chill",
                "Bien random todo",
                "Ni en mi mejor sueno",
                "Que rolon",
                "Estas bien crack",
                "Quede 😔",
                "Vamo' a calmarno'",
                "¿Y el crush? Bien, gracias",
                "No te lo voy a negar",
                "No soy toxico, soy intenso",
                "De chill",
                "Te pasaste de lanza",
                "Quiero ser un sticker",
                "Es de chill, bro",
                "¿Me estas albureando?",
                "Esto ya es personal",
                "Modo oscuro activado",
                "Meh",
                "No traigo datos",
                "Eres un NPC",
                "Alta referencia",
                "No digas mamad**s, Mary Jane",
                "Se tenia que quemar",
                "Yo solo queria dormir",
                "Tamo' activos",
                "Full HD 4K",
                "Estas modo historia",
                "Me da ansiedad",
                "Y el que entendio, entendio",
                "Andamos modo vago",
                "Ya se armo la carnita asada",
                "Que oso",
                "Estoy en modo fantasma",
                "Esto ya no es un juego",
                "No me quemes",
                "Fue sin querer queriendo",
                "Siento que ya vivi esto",
                "Ya me voy a dormir, neta",
                "¿Que se cuenta el algoritmo?",
                "Cringe total",
                "Soy un personaje secundario",
                "A dormir que manana hay que fallar de nuevo",
                "Estoy en mi era silenciosa",
                "Esto se va a descontrolar",
                "Mas falso que influencer sin filtro",
                "Y si lo sone todo?",
                "No es por drama, pero si es por drama",
                "Chismecito sabroso",
                "Modo sad on",
                "Modo fresco activado",
                "Ahorita ando ocupadx, siendo feliz",
                "No te odio, solo no te quiero cerca",
                "Se va a descontrolar esto",
                "La vida es un meme",
                "Dejen de romantizar el estres",
                "Que duro, bro",
                "Tremendo flow",
                "No se, Rick...",
                "No estoy bien, pero sigo de pie",
                "Que alguien me adopte",
                "Estas muy basado",
                "No es tendencia, es estilo de vida",
                "Modo vacaciones mental",
                "¿Y si mejor no?",
                "Estoy offline emocionalmente",
                "Esa no me la sabia",
                "Con esa carita quien te dice que no",
                "Ya fue, ya dolio, ahora que valga la pena",
                "Pintamos toda la casa...",
                "¿Quieres ver magia?"
            };
    
    public static String abecedario = "qwertyuiopasdfghjklzxcvbnm";
    

}
